services:
  npm:
    build: .
    image: node:21
    container_name: frontend
    ports:
      - "3000:3000"
    environment:
      REACT_APP_API_URL: 'https://metamesh-spring-app-metamesh-api.azuremicroservices.io/api'