name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main # Branche principale à surveiller pour le déploiement
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy Frontend
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16' # Version Node.js (choisir celle utilisée par votre projet)

    - name: Install Dependencies
      run: |
        npm install
        npm run build # Commande pour compiler votre frontend

    - name: Deploy to Azure Static Web App
      uses: Azure/static-web-apps-deploy@v1
      with:
        azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
        repo_token: ${{ secrets.GITHUB_TOKEN }} # Autorisation GitHub
        action: "upload"
        app_location: "/" # Chemin vers votre code source
        output_location: "build" # Dossier généré après la compilation (ex. : build, dist)
