name: Deploy Frontend to Azure Static Web Apps

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Récupère le code source
      - name: Checkout code
        uses: actions/checkout@v2

      # 2. Configurer Node.js (pour builder le projet React)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 21

      # 3. Installer les dépendances et builder le projet
      - name: Install and Build Frontend
        run: |
          npm install
          npm run build

      # 4. Déployer sur Azure Static Web Apps
      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          app_location: "/" # Emplacement du projet (racine)
          output_location: "build" # Dossier de sortie (généré par npm run build)
          action: "upload" # Action de déploiement
